spring:
  datasource:
    # MySQL JDBC 드라이버 클래스 지정
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        # 실행되는 SQL 쿼리를 로그에 포맷팅 후 출력
        format_sql: true
        # SQL 쿼리에 어떤 JPQL이 생성됐는지 주석을 함께 출력
        use_sql_comments: true

  profiles:
    # 기본 활성화 프로파일 지정 (로컬 개발 시 local, EC2 배포 시 prod로 전환)
    active: local

logging:
  level:
    # Hibernate가 실행하는 SQL 쿼리를 DEBUG 레벨로 콘솔에 출력
    org.hibernate.SQL: debug